### ISSUE TITLE
undefined method nan? for Fixnum

### ISSUE THREAD

**Issue by romanvbabenko** [vicentllongo/simplecov-json#7]
.rvm/gems/ruby-2.0.0-p247/gems/simplecov-json-0.2/lib/simplecov-json.rb:17:in `block in format': undefined method`nan?' for 0:Fixnum (NoMethodError)

**Comment by guiman** [comment]
This only happens on older version of `simplecov` because of https://github.com/colszowka/simplecov/blob/v0.8.2/lib/simplecov/file_list.rb#L40-L43 but it's sorted in https://github.com/colszowka/simplecov/blob/v0.9.0/lib/simplecov/file_list.rb#L42-L45
